#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Decision.Common.HtmlHelpers;
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmpRelative/List.cshtml")]
    public partial class _Views_EmpRelative_List_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.EmpRelative.EmpRelativeListViewModel>
    {
        public _Views_EmpRelative_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\EmpRelative\List.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-ajax=\"true\"");

WriteLiteral(" data-ajax-mode=\"replace\"");

WriteLiteral(" data-ajax-success=\"onSuccessFormValidation(data, status, xhr,\'createAddressForm\'" +
",\'modal\')\"");

WriteLiteral("\r\n                   data-ajax-update=\"#modal\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" role=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>درج آدرس جدید</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"addressList\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\EmpRelative\List.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\EmpRelative\List.cshtml"
               Html.RenderPartial(MVC.EmpRelative.Views.ViewNames._ListAjax, Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-footer padding-5-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-8\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" data-page=\"2\"");

WriteLiteral(" data-json=\'{\"ApplicantId\":\"");

            
            #line 21 "..\..\Views\EmpRelative\List.cshtml"
                                                            Write(Model.Request.Empno);

            
            #line default
            #line hidden
WriteLiteral("\"}\'");

WriteLiteral(" data-container=\"#addressList\"");

WriteLiteral("\r\n                        data-progress=\"#progress\"");

WriteLiteral("\r\n                        data-load-url=\"");

            
            #line 23 "..\..\Views\EmpRelative\List.cshtml"
                                  Write(Url.Action(MVC.Address.ListAjax()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                        onclick=\"justPaging(this)\"");

WriteLiteral(" class=\"btn btn-info btn-block btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                    بیشتر\r\n                </button>\r\n            </div>\r\n    " +
"    </div>\r\n        <div");

WriteLiteral(" id=\"progress\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1399), Tuple.Create("\"", 1449)
            
            #line 30 "..\..\Views\EmpRelative\List.cshtml"
, Tuple.Create(Tuple.Create("", 1405), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/images/loading.gif")
            
            #line default
            #line hidden
, 1405), false)
);

WriteLiteral(" alt=\"loading...\"");

WriteLiteral("/>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("Menu", () => {

            
            #line 34 "..\..\Views\EmpRelative\List.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 35 "..\..\Views\EmpRelative\List.cshtml"
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\EmpRelative\List.cshtml"
          Html.RenderPartial(MVC.Employee.Views._EmployeeRelatedLinksBuilder, Model.Request.Empno);
            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

});

WriteLiteral("    ");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Views\EmpRelative\List.cshtml"
   Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
