#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Decision.Common.HtmlHelpers;
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/OtherBime/_OtherBimeItem.cshtml")]
    public partial class _Views_OtherBime__OtherBimeItem_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.OtherBime.OtherBimeViewModel>
    {
        public _Views_OtherBime__OtherBimeItem_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"col-md-12 data-item\"");

WriteAttribute("id", Tuple.Create(" id=\"", 88), Tuple.Create("\"", 115)
, Tuple.Create(Tuple.Create("", 93), Tuple.Create("OtherBime-", 93), true)
            
            #line 2 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
, Tuple.Create(Tuple.Create("", 103), Tuple.Create<System.Object, System.Int32>(Model.Empno
            
            #line default
            #line hidden
, 103), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <label>وضعیت بیمه </label>\r\n                    <small>\r\n");

            
            #line 10 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                         if (Model.IsEnable)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <i");

WriteLiteral(" class=\"fa fa-check-square text-success\"");

WriteLiteral(" title=\"فعال\"");

WriteLiteral("></i>\r\n");

            
            #line 13 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <i");

WriteLiteral(" class=\"fa fa-check-square-o text-muted\"");

WriteLiteral(" title=\"غیر فعال\"");

WriteLiteral("></i>\r\n");

            
            #line 17 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </small>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">نوع بیمه:</label>\r\n                    <small>");

            
            #line 23 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                      Write(Model.BimeDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">سال و ماه شروع:</label>\r\n                    <small>");

            
            #line 27 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                      Write(Model.StartYear.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 27 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                                                          Write(Model.StartMonth.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral(" </small>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">سال و ماه پایان:</label>\r\n                    <small>");

            
            #line 31 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                      Write(Model.EndYear.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 31 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                                                        Write(Model.EndMonth.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral(" </small>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">شماره بیمه:</label>\r\n                    <small>");

            
            #line 35 "..\..\Views\OtherBime\_OtherBimeItem.cshtml"
                      Write(Model.InsNo.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n    </div" +
">\r\n</div>");

        }
    }
}
#pragma warning restore 1591
