#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decision.Web.Views.MontlyResult
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Decision.Common.HtmlHelpers;
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MontlyResult/_ListAjax.cshtml")]
    public partial class _ListAjax : System.Web.Mvc.WebViewPage<Decision.ViewModel.MontlyResult.MontlyResultListViewModel>
    {
        public _ListAjax()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"timeline\"");

WriteLiteral(">\r\n        <!-- Line component -->\r\n        <div");

WriteLiteral(" class=\"line text-muted\"");

WriteLiteral("></div>\r\n\r\n");

            
            #line 8 "..\..\Views\MontlyResult\_ListAjax.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\MontlyResult\_ListAjax.cshtml"
         foreach (var eYearGroup in Model.MontlyResults.GroupBy(e => e.ResultYear))
        {

            
            #line default
            #line hidden
WriteLiteral("        <article");

WriteLiteral(" class=\"timeline panel  panel-primary\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <!-- Icon -->\r\n                <div");

WriteLiteral(" class=\"panel-heading icon\"");

WriteLiteral(">\r\n\r\n                    <a");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-controls=\"show-search\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteAttribute("href", Tuple.Create(" href=\"", 609), Tuple.Create("\"", 651)
, Tuple.Create(Tuple.Create("", 616), Tuple.Create("#show-monthlyresult-", 616), true)
            
            #line 15 "..\..\Views\MontlyResult\_ListAjax.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 636), Tuple.Create<System.Object, System.Int32>(eYearGroup.Key
            
            #line default
            #line hidden
, 636), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 16 "..\..\Views\MontlyResult\_ListAjax.cshtml"
                   Write(eYearGroup.Key);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n\r\n                </div>\r\n                <div");

WriteAttribute("id", Tuple.Create(" id=\"", 768), Tuple.Create("\"", 807)
, Tuple.Create(Tuple.Create("", 773), Tuple.Create("show-monthlyresult-", 773), true)
            
            #line 20 "..\..\Views\MontlyResult\_ListAjax.cshtml"
, Tuple.Create(Tuple.Create("", 792), Tuple.Create<System.Object, System.Int32>(eYearGroup.Key
            
            #line default
            #line hidden
, 792), false)
);

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" aria-labelledby=\"heading1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\MontlyResult\_ListAjax.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\MontlyResult\_ListAjax.cshtml"
                         foreach (var e in eYearGroup.ToList())
                        {
                            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\MontlyResult\_ListAjax.cshtml"
                       Write(Html.Partial(MVC.MontlyResult.Views._MontlyResultItem, e));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\MontlyResult\_ListAjax.cshtml"
                                                                                      
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </div>\r\n        <" +
"/article>\r\n");

            
            #line 30 "..\..\Views\MontlyResult\_ListAjax.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
