#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Employee\Details.cshtml"
    using Decision.Common.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Employee\Details.cshtml"
    using Decision.DomainClasses.Entities.Employee;
    
    #line default
    #line hidden
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Employee/Details.cshtml")]
    public partial class _Views_Employee_Details_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.Employee.EmployeeDetailsViewModel>
    {
        public _Views_Employee_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Employee\Details.cshtml"
  
    ViewBag.Title = "مشاهده جزئیات کارکنان";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">اطلاعات متقاضی</h3>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"center-block text-center\"");

WriteLiteral(">\r\n                            <figure>\r\n");

WriteLiteral("                                ");

            
            #line 22 "..\..\Views\Employee\Details.cshtml"
                           Write(Html.Image(Model.Photo, Model.Family+" "+Model.Name, "img-circle img-responsive img-thumbnail", 200));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <figcaption>\r\n                                 " +
"   <h5>\r\n");

WriteLiteral("                                        ");

            
            #line 25 "..\..\Views\Employee\Details.cshtml"
                                   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 25 "..\..\Views\Employee\Details.cshtml"
                                               Write(Model.Family);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <br>\r\n                                 " +
"   </h5>\r\n");

            
            #line 28 "..\..\Views\Employee\Details.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Employee\Details.cshtml"
                                     if (Model.SexCod == "SEX01")//GenderType.Male)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <i");

WriteLiteral(" class=\"fa fa-male\"");

WriteLiteral(" title=\"مرد\"");

WriteLiteral("></i>\r\n");

            
            #line 31 "..\..\Views\Employee\Details.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <i");

WriteLiteral(" class=\"fa fa-female\"");

WriteLiteral(" title=\"زن\"");

WriteLiteral("></i>\r\n");

            
            #line 35 "..\..\Views\Employee\Details.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <br />\r\n                                    <" +
"div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"StopStat\"");

WriteLiteral(">وضعیت پرسنل:</label>\r\n                                        <small");

WriteLiteral(" id=\"StopStat\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Employee\Details.cshtml"
                                                        Write(Html.DisplayFor(a => a.StopStat));

            
            #line default
            #line hidden
WriteLiteral(@"</small>
                                    </div>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"line-status\"");

WriteLiteral(">\r\n                            <small");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n                                اطلاعات فردی\r\n                            " +
"</small>\r\n                        </h3>\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"LastFamily\"");

WriteLiteral(">نام خانوادگی قبلی:</label>\r\n                                <small");

WriteLiteral(" id=\"LastFamily\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.LastFamily);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IdNo\"");

WriteLiteral(">شماره شناسنامه:</label>\r\n                                <small");

WriteLiteral(" id=\"IdNo\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Employee\Details.cshtml"
                                            Write(Model.IdNo.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IdNoContinued\"");

WriteLiteral(">شماره مسلسل شناسنامه:</label>\r\n                                <small");

WriteLiteral(" id=\"IdNoContinued\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Employee\Details.cshtml"
                                                     Write(Model.IdNoContinued.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"BirthDate\"");

WriteLiteral(">تاریخ تولد:</label>\r\n                                <small");

WriteLiteral(" id=\"BirthDate\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.BirthDate.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"MelliCode\"");

WriteLiteral(">کد ملی:</label>\r\n                                <small");

WriteLiteral(" id=\"MelliCode\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.MelliCode.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"BirthCityCod\"");

WriteLiteral(">محل تولد:</label>\r\n                                <small");

WriteLiteral(" id=\"BirthCityCod\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\Employee\Details.cshtml"
                                                    Write(Model.BirthCity);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IssueCityCod\"");

WriteLiteral(">محل صدور:</label>\r\n                                <small");

WriteLiteral(" id=\"IssueCityCod\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Employee\Details.cshtml"
                                                    Write(Model.IssueCity);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"ReligionCod\"");

WriteLiteral(">دین:</label>\r\n                                <small");

WriteLiteral(" id=\"ReligionCod\"");

WriteLiteral(">");

            
            #line 90 "..\..\Views\Employee\Details.cshtml"
                                                   Write(Model.Religion);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"    row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"line-status\"");

WriteLiteral(">\r\n                            <small>\r\n                                <i");

WriteLiteral(" class=\"fa fa-graduation-cap\"");

WriteLiteral("></i>\r\n                                وضعیت شغلی تحصیلی\r\n                       " +
"     </small>\r\n                        </h3>\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"line-status\"");

WriteLiteral(">\r\n                            <small>\r\n                                <i");

WriteLiteral(" class=\"fa fa-credit-card\"");

WriteLiteral("></i>\r\n                                سایر مشخصات\r\n                            <" +
"/small>\r\n                        </h3>\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n\r\n            </div>\r\n        </div>\r\n        ");

WriteLiteral("\r\n    </div>\r\n\r\n</div>\r\n\r\n");

DefineSection("Menu", () => {

WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
