#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Employee\Details.cshtml"
    using Decision.Common.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Employee\Details.cshtml"
    using Decision.DomainClasses.EmployeeEntities;
    
    #line default
    #line hidden
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Employee/Details.cshtml")]
    public partial class _Views_Employee_Details_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.Employee.EmployeeDetailsViewModel>
    {
        public _Views_Employee_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Employee\Details.cshtml"
  
    ViewBag.Title = "مشاهده جزئیات کارکنان";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">اطلاعات متقاضی</h3>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"center-block text-center\"");

WriteLiteral(">\r\n                            <figure>\r\n");

WriteLiteral("                                ");

            
            #line 22 "..\..\Views\Employee\Details.cshtml"
                           Write(Html.Image(Model.Photo, Model.Family + " " + Model.Name, "img-circle img-responsive img-thumbnail", 200));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <figcaption>\r\n                                 " +
"   <h5>\r\n");

WriteLiteral("                                        ");

            
            #line 25 "..\..\Views\Employee\Details.cshtml"
                                   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 25 "..\..\Views\Employee\Details.cshtml"
                                               Write(Model.Family);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <br>\r\n                                 " +
"   </h5>\r\n");

            
            #line 28 "..\..\Views\Employee\Details.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Employee\Details.cshtml"
                                     if (Model.SexCod == "SEX01")//GenderType.Male)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <i");

WriteLiteral(" class=\"fa fa-male\"");

WriteLiteral(" title=\"مرد\"");

WriteLiteral("></i>\r\n");

            
            #line 31 "..\..\Views\Employee\Details.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <i");

WriteLiteral(" class=\"fa fa-female\"");

WriteLiteral(" title=\"زن\"");

WriteLiteral("></i>\r\n");

            
            #line 35 "..\..\Views\Employee\Details.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <br />\r\n                                    <" +
"div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"StopStat\"");

WriteLiteral(">وضعیت پرسنل:</label>\r\n                                        <small");

WriteLiteral(" id=\"StopStat\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Employee\Details.cshtml"
                                                        Write(Html.DisplayFor(a => a.StopStatE ));

            
            #line default
            #line hidden
WriteLiteral(@"</small>
                                    </div>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"line-status\"");

WriteLiteral(">\r\n                            <small");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n                                اطلاعات فردی\r\n                            " +
"</small>\r\n                        </h3>\r\n                       <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"LastFamily\"");

WriteLiteral(">نام خانوادگی قبلی:</label>\r\n                                <small");

WriteLiteral(" id=\"LastFamily\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.LastFamily);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IdNo\"");

WriteLiteral(">شماره شناسنامه:</label>\r\n                                <small");

WriteLiteral(" id=\"IdNo\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Employee\Details.cshtml"
                                            Write(Model.IdNo.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IdNoContinued\"");

WriteLiteral(">شماره مسلسل شناسنامه:</label>\r\n                                <small");

WriteLiteral(" id=\"IdNoContinued\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Employee\Details.cshtml"
                                                     Write(Model.IdNoContinued.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"BirthDate\"");

WriteLiteral(">تاریخ تولد:</label>\r\n                                <small");

WriteLiteral(" id=\"BirthDate\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.BirthDate.GetDatePersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"MelliCode\"");

WriteLiteral(">کد ملی:</label>\r\n                                <small");

WriteLiteral(" id=\"MelliCode\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.MelliCode.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"BirthCityCod\"");

WriteLiteral(">محل تولد:</label>\r\n                                <small");

WriteLiteral(" id=\"BirthCityCod\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\Employee\Details.cshtml"
                                                    Write(Model.BirthCity);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IssueCityCod\"");

WriteLiteral(">محل صدور:</label>\r\n                                <small");

WriteLiteral(" id=\"IssueCityCod\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Employee\Details.cshtml"
                                                    Write(Model.IssueCity);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"ReligionDsc\"");

WriteLiteral(">دین:</label>\r\n                                <small");

WriteLiteral(" id=\"ReligionDsc\"");

WriteLiteral(">");

            
            #line 90 "..\..\Views\Employee\Details.cshtml"
                                                   Write(Model.ReligionDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"EmpType\"");

WriteLiteral(">نوع استخدام:</label>\r\n                                <small");

WriteLiteral(" id=\"EmpType\"");

WriteLiteral(">");

            
            #line 96 "..\..\Views\Employee\Details.cshtml"
                                               Write(Model.EmpType);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"MarriageDsc\"");

WriteLiteral(">وضعیت تاهل:</label>\r\n                                <small");

WriteLiteral(" id=\"MarriageDsc\"");

WriteLiteral(">");

            
            #line 100 "..\..\Views\Employee\Details.cshtml"
                                                   Write(Model.MarriageDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"MarriDate\"");

WriteLiteral(">تاریخ ازدواج:</label>\r\n                                <small");

WriteLiteral(" id=\"MarriDate\"");

WriteLiteral(">");

            
            #line 104 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.MarriDate.GetDatePersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"NoChild\"");

WriteLiteral(">تعداد فرزندان:</label>\r\n                                <small");

WriteLiteral(" id=\"NoChild\"");

WriteLiteral(">");

            
            #line 108 "..\..\Views\Employee\Details.cshtml"
                                               Write(Model.NoChild);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"RealPlace\"");

WriteLiteral(">محل خدمت:</label>\r\n                                <small");

WriteLiteral(" id=\"RealPlace\"");

WriteLiteral(">");

            
            #line 114 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.RealPlace);

            
            #line default
            #line hidden
WriteLiteral(" </small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"Unit\"");

WriteLiteral(">مرکز هزینه:</label>\r\n                                <small");

WriteLiteral(" id=\"Unit\"");

WriteLiteral(">");

            
            #line 118 "..\..\Views\Employee\Details.cshtml"
                                            Write(Model.Unit);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"GovEmpDate\"");

WriteLiteral(">تاریخ استخدام:</label>\r\n                                <small");

WriteLiteral(" id=\"GovEmpDate\"");

WriteLiteral(">");

            
            #line 124 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.GovEmpDate.GetDatePersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"ManEmpDate\"");

WriteLiteral(">تاریخ ورود به شهرداری:</label>\r\n                                <small");

WriteLiteral(" id=\"ManEmpDate\"");

WriteLiteral(">");

            
            #line 128 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.ManEmpDate.GetDatePersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"IssueCityCod\"");

WriteLiteral(">سنوات حکم:</label>\r\n                                <small");

WriteLiteral(" id=\"IssueCityCod\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\Employee\Details.cshtml"
                                                    Write(Model.SanavatHokm.GetDatePersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"ReligionCod\"");

WriteLiteral(">سنوات حقوق:</label>\r\n                                <small");

WriteLiteral(" id=\"ReligionCod\"");

WriteLiteral(">");

            
            #line 136 "..\..\Views\Employee\Details.cshtml"
                                                   Write(Model.SanavatHoghogh.GetDatePersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"NationalDsc\"");

WriteLiteral(">ملیت:</label>\r\n                                <small");

WriteLiteral(" id=\"NationalDsc\"");

WriteLiteral(">");

            
            #line 142 "..\..\Views\Employee\Details.cshtml"
                                                   Write(Model.NationalDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"TelNo\"");

WriteLiteral(">تلفن منزل:</label>\r\n                                <small");

WriteLiteral(" id=\"TelNo\"");

WriteLiteral(">");

            
            #line 146 "..\..\Views\Employee\Details.cshtml"
                                             Write(Model.TelNo.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"Mobile\"");

WriteLiteral(">تلفن همراه:</label>\r\n                                <small");

WriteLiteral(" id=\"Mobile\"");

WriteLiteral(">");

            
            #line 150 "..\..\Views\Employee\Details.cshtml"
                                              Write(Model.Mobile.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"MainTelNo\"");

WriteLiteral(">تلفن ضروری:</label>\r\n                                <small");

WriteLiteral(" id=\"MainTelNo\"");

WriteLiteral(">");

            
            #line 154 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.MainTelNo.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"Addr\"");

WriteLiteral(">آدرس:</label>\r\n                                <small");

WriteLiteral(" id=\"Addr\"");

WriteLiteral(">");

            
            #line 160 "..\..\Views\Employee\Details.cshtml"
                                            Write(Model.Addr);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"ZipNo\"");

WriteLiteral(">کد پستی:</label>\r\n                                <small");

WriteLiteral(" id=\"ZipNo\"");

WriteLiteral(">");

            
            #line 164 "..\..\Views\Employee\Details.cshtml"
                                             Write(Model.ZipNo.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"Email\"");

WriteLiteral(">آدرس الکترونیک:</label>\r\n                                <small");

WriteLiteral(" id=\"Email\"");

WriteLiteral(">");

            
            #line 170 "..\..\Views\Employee\Details.cshtml"
                                             Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"NezStatDsc\"");

WriteLiteral(">وضعیت نظام وظیفه:</label>\r\n                                <small");

WriteLiteral(" id=\"NezStatDsc\"");

WriteLiteral(">");

            
            #line 174 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.NezStatDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"LDegreeDsc\"");

WriteLiteral(">آخرین مقطع تحصیلی:</label>\r\n                                <small");

WriteLiteral(" id=\"LDegreeDsc\"");

WriteLiteral(">");

            
            #line 178 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.LDegreeDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"LMajorDsc\"");

WriteLiteral(">آخرین مدرک تحصیلی:</label>\r\n                                <small");

WriteLiteral(" id=\"LMajorDsc\"");

WriteLiteral(">");

            
            #line 182 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.LMajorDsc.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"Acc\"");

WriteLiteral(">شماره حساب:</label>\r\n                                <small");

WriteLiteral(" id=\"Acc\"");

WriteLiteral(">");

            
            #line 188 "..\..\Views\Employee\Details.cshtml"
                                           Write(Model.Acc.GetPersianNumber());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"InsTypeDsc\"");

WriteLiteral(">وضعیت بیمه:</label>\r\n                                <small");

WriteLiteral(" id=\"InsTypeDsc\"");

WriteLiteral(">");

            
            #line 192 "..\..\Views\Employee\Details.cshtml"
                                                  Write(Model.InsTypeDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"InsNo\"");

WriteLiteral(">شماره بیمه:</label>\r\n                                <small");

WriteLiteral(" id=\"InsNo\"");

WriteLiteral(">");

            
            #line 196 "..\..\Views\Employee\Details.cshtml"
                                             Write(Model.InsNo);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"BloodDsc\"");

WriteLiteral(">گروه خونی:</label>\r\n                                <small");

WriteLiteral(" id=\"BloodDsc\"");

WriteLiteral(">");

            
            #line 200 "..\..\Views\Employee\Details.cshtml"
                                                Write(Model.BloodDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n\r\n                        </div>\r\n " +
"                       <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"HealthDsc\"");

WriteLiteral(">وضعیت سلامتی:</label>\r\n                                <small");

WriteLiteral(" id=\"HealthDsc\"");

WriteLiteral(">");

            
            #line 207 "..\..\Views\Employee\Details.cshtml"
                                                 Write(Model.HealthDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"HouseDsc\"");

WriteLiteral(">وضعیت خانه:</label>\r\n                                <small");

WriteLiteral(" id=\"HouseDsc\"");

WriteLiteral(">");

            
            #line 211 "..\..\Views\Employee\Details.cshtml"
                                                Write(Model.HouseDsc);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"LPostEblagh\"");

WriteLiteral(">آخرین پست سازمانی:</label>\r\n                                <small");

WriteLiteral(" id=\"LPostEblagh\"");

WriteLiteral(">");

            
            #line 215 "..\..\Views\Employee\Details.cshtml"
                                                   Write(Model.LPostEblagh);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                            </div>\r\n                        </div>\r\n   " +
"                 </div>\r\n\r\n\r\n\r\n                </div>\r\n            </div>\r\n     " +
"       <div");

WriteLiteral(" class=\" row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"line-status\"");

WriteLiteral(">\r\n                        <small>\r\n                            <i");

WriteLiteral(" class=\"fa fa-graduation-cap\"");

WriteLiteral("></i>\r\n                            وضعیت شغلی تحصیلی\r\n                        </s" +
"mall>\r\n                    </h3>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"line-status\"");

WriteLiteral(">\r\n                        <small>\r\n                            <i");

WriteLiteral(" class=\"fa fa-credit-card\"");

WriteLiteral("></i>\r\n                            سایر مشخصات\r\n                        </small>\r" +
"\n                    </h3>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n  " +
"      </div>\r\n    </div>\r\n    ");

WriteLiteral("\r\n</div>\r\n\r\n</div>\r\n\r\n");

DefineSection("Menu", () => {

WriteLiteral("\r\n");

            
            #line 263 "..\..\Views\Employee\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 263 "..\..\Views\Employee\Details.cshtml"
      Html.RenderPartial(MVC.Employee.Views._EmployeeRelatedLinksBuilder, Model.Empno);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
